ccflags-y = -Wall -I$(src)/include $(CFLAGS_DBG)

# uartdev_core chứa các APIs chung, được dùng trong nhiều UART device driver.

obj-m	+= uartdev_core.o
uartdev_core-objs := src/drv.o src/uif.o src/uart.o

# counter_vn29a80: UART device driver cho bộ đếm vn29a80
obj-m	+= counter_vn29a80.o
counter_vn29a80-objs := src/vn29a80_drv.o src/vn29a80_req.o
